### ISSUE TITLE
Support for public_url when building 

### ISSUE THREAD

**Issue by DingDean** [zineland/zine#11]
# What's the problem?

I'm using Zine version 0.2.1. I can't publish the build to Github Pages because the link to assets files are wrong.

When deploying to Github Pages, it's required that our assets url should be prefixed by the project name of our project. 

# How to reproduce the issue?

* Initiate and build a simple zine project
* use github action to publish the build, currently I'm using a really simple flow config file: https://github.com/DingDean/zine-blog-test/blob/master/.github/workflows/publish.yml
* visit the github page link and you'll find the page is only rendered with raw html, without any css. 

# What's to be expected?

Can Zine provides a configuration `public_url` when building our magazine so that all the assets can be rightly prefixed?

**Comment by Folyd** [comment]
Thanks for the feedback. We'll fix this ASAP.

Also, you can add a custom domain to Github pages to avoid path issues.
