### ISSUE TITLE
add "canonical" link in header with support for specifying alternate for articles.

### ISSUE THREAD

**Issue by Bas-Man** [zineland/zine#141]
Currently there does not appear to be a canonical link in the `<head>..</head>` section.

```
<link rel=canonical href=https://some.urk.link/page>
```
This link would generally be the same as the actual page. 

However when republishing an article it would be best to allow the author to reference their original site. This is done by serveral other sites such as https://dev.to 
See example [here](https://dev.to/basman/deconstructing-spf-records-with-rust-4e9o)

It would be good to have a way to override this on a per article bases when republishing an existing article from  another source. Of course this needs to be done with the original authors permission. The information for this could be stored in the article TOML 
data.

```
[[article]]
path = "/announcing"
file = "announcing.md"
title = "Announcing Rust Magazine"
author = "rust-magazine"
topic = ["announcement"]
pub_date = "2022-12-10"
canonical = "https://original.url/refernce"
publish = true
featured = true
i18n.zh = { path = "/announcing-zh", file = "announcing-zh.md", title = "宣布 Rust 杂志", author = ["folyd", "rust-magazine"] }
```

The canonical will help with google search results and allow the author to reference their original article link.

**Comment by Folyd** [comment]
Sounds great. Thanks for the suggestions. 👍
