### ISSUE TITLE
Improve OG description parsing

### ISSUE THREAD

**Issue by Folyd** [zineland/zine#158]
Currently, the https://rustmagazine.org/issue-1/ has been parse to "Dear Rustaceans,", we need improvement.

**Comment by kiyov09** [comment]
@Folyd 
I'm interested in this one too. I want to start helping on the rust side of things.

**Comment by kiyov09** [comment]
Yeap. I was taking a look at that function previously. It works fine but only returns up to 200 chars of the first meaningful line.
In this case "Dear Rustaceans," is the whole line.
What do you think should be the new behavior?

**Comment by Folyd** [comment]
I don't think `the first meaningful line` is enough, such as in this case. The better approach is to extract at most 200 chars no matter how many lines.

**Comment by kiyov09** [comment]
Should I close this now?

**Comment by Folyd** [comment]
Close via #170.
