### ISSUE TITLE
Fix mobile UI messy

### ISSUE THREAD

**Issue by Folyd** [zineland/zine#160]
![](https://i.imgur.com/k2alyng.jpg)

**Comment by kiyov09** [comment]
I think I can help with this one. Let me know.

**Comment by Folyd** [comment]
Thanks, @kiyov09. zine uses Tailwind CSS to style the UI, here are the source lines related to this issue:
https://github.com/zineland/zine/blob/b30658884c50d6093871f43e7492879460151f27/templates/issue.jinja#L22-L47

**Comment by kiyov09** [comment]
Awesome. I'll start working on a solution right away. Is there anything I need to know before opening a PR?

**Comment by Folyd** [comment]
Great, nothing else needs to know, feel free to open PR. 👍

**Comment by kiyov09** [comment]
@Folyd 
Just opened a PR for this issue #163
