### ISSUE TITLE
Discussion: zine.toml for [Site] logo data field

### ISSUE THREAD

**Issue by Bas-Man** [zineland/zine#169]
According the the documentation. The [Site] data has a `logo` field which is the path to the `favicon`

1. I think it might be better and more clear to have this actually named `favicon`. However I think this can be further improved upon with the next comment.
2. Today most sites provide multiple favicon images. This would suggest that providing a custom_header file that can be injected between the `<head></head>` tags would be the best place for site owner to manage favicons.

Thoughts?

**Comment by Folyd** [comment]
1. The `logo` field has been removed, 😅  see https://github.com/zineland/zine/commit/e0aa6cd371f0b741f3cae81e631b66cfa861ee0a

2. We already support `head_template` in `[theme]` section.

```toml
[theme]
head_template = "templates/head.html"
```
This is the custom head for Rust Magazine:
https://github.com/RustMagazine/rustmagazine/blob/bb2535ec7f27b9d8fb31bfc8f521518cfae48f47/templates/head.html

**Comment by Bas-Man** [comment]
I should have looked around. But at least I am learning more about the code base :)

Thanks.
