### ISSUE TITLE
Zine V0.14.0 / Panic on Start / Using master rustmagazine

### ISSUE THREAD

**Issue by Bas-Man** [zineland/zine#217]
```sh
listening on http://127.0.0.1:3000
thread 'tokio-runtime-worker' panicked at 'Failed to render author page: could not render include: error in "footer_template.jinja" (in base.jinja:54)

Caused by:
    unknown filter: filter date is unknown (in footer_template.jinja:51)', src/entity/zine.rs:411:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Watch build error: task 10 panicked
```
Running on Mac Using latest brew install.

**Comment by Folyd** [comment]
Thanks, @Bas-Man.  We migrated from `tera` to `minijinja` via https://github.com/zineland/zine/pull/214, `minijinja` has no built-in filter called `date`, so it panicked. One of solution is to remove the `date` filter, see also: https://github.com/RustMagazine/rustmagazine/pull/88/files
