### ISSUE TITLE
content didn't build when build finished 

### ISSUE THREAD

**Issue by codering** [zineland/zine#220]
`zine serve` works OK, but when `zine build . docs` , it didn't generate any issues.

<img width="155" alt="image" src="https://github.com/zineland/zine/assets/2271825/45e4c6c6-a361-4877-b08f-a7ec6274e0ea">

<img width="1068" alt="image" src="https://github.com/zineland/zine/assets/2271825/99a59c40-be4c-4bc4-8eaf-d4164ea7ae39">

zine -- 0.15

**Comment by codering** [comment]
Am I missing some configuration？

**Comment by Folyd** [comment]
Hi, @codering. You should set `publish = true` to render the issue, and set `featured = true` to feature the article in an issue.
See https://github.com/RustMagazine/rustmagazine/blob/main/content/issue-3/zine.toml#L8 and https://github.com/RustMagazine/rustmagazine/blob/main/content/issue-3/zine.toml#L17

**Comment by codering** [comment]
Thank you, it works. 
However, I have another issue where the background image URL is incorrect when building. 
I found this problem mentioned in this pull request: https://github.com/zineland/zine/pull/28, but it still remains unresolved for me.
